
spring:
  datasource:
    url: jdbc:mysql://localhost/test?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
    username: root
    password: 548983
    driver-class-name: com.mysql.cj.jdbc.Driver